### ISSUE TITLE
weight_streetnet returning error

### ISSUE THREAD

**Issue by ttuff** [cran/dodgr#1]
weight_streetnet has started throwing an error. This includes the example code in the documentation. It now throws the following error. Any suggestions?
Error in cbind(as.numeric(obj[, xy_cols[1]]), as.numeric(obj[, xy_cols[2]])) : 'list' object cannot be coerced to type 'double'

> library (osmdata)
> dat <- opq ("hampi india") %>%
+     add_osm_feature (key = "highway") %>%
+     osmdata_sc ()
> graph <- weight_streetnet (dat)
Error in cbind(as.numeric(obj[, xy_cols[1]]), as.numeric(obj[, xy_cols[2]])) : 
  'list' object cannot be coerced to type 'double'
> from <- sample (graph$.vx0, size = 100)
Error in sample.int(length(x), size, replace, prob) : 
  invalid first argument
> tlim <- c (5, 10, 20, 30, 60) * 60 # times in seconds
> x <- dodgr_isochrones (graph, from = from, tlim)
Error in dodgr_isochrones(graph, from = from, tlim) : 
  isochrones can only be calculated from SC-class networks generated by osmdata_sc.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the `DESCRIPTION` file for the package authors and potentially URLs. Thanks!
